### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by daynefiler** [m-clark/confusionMatrix#7]
I think this would be a nice addition, and then allow others to incorporate the functionality into their packages. Happy to help if you'd like.

**Comment by m-clark** [comment]
Hi @daynefiler, thanks for the suggestion and sorry for the belated response. I'd be up for this, but I was intending to refactor this once I got some time, and also to see if I could take advantage of the latest dplyr developments.  Keep an eye out in the future.
